import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @fadil dayak
 */
public class AplikasiKonversiSuhuFrame extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKonversiSuhuFrame
     */
    public AplikasiKonversiSuhuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgKonversi = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        LJudul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TSuhu = new javax.swing.JTextField();
        CbSkalaSuhu = new javax.swing.JComboBox<>();
        Rb1 = new javax.swing.JRadioButton();
        Rb2 = new javax.swing.JRadioButton();
        Rb3 = new javax.swing.JRadioButton();
        BKonversi = new javax.swing.JButton();
        LHasil = new javax.swing.JLabel();
        Rb4 = new javax.swing.JRadioButton();
        THasil = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 102));

        LJudul.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LJudul.setForeground(new java.awt.Color(51, 51, 51));
        LJudul.setText("Aplikasi Konversi ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Input Suhu Ji Awal");

        TSuhu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSuhuActionPerformed(evt);
            }
        });
        TSuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TSuhuKeyTyped(evt);
            }
        });

        CbSkalaSuhu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CbSkalaSuhu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        CbSkalaSuhu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbSkalaSuhuItemStateChanged(evt);
            }
        });
        CbSkalaSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbSkalaSuhuActionPerformed(evt);
            }
        });

        BgKonversi.add(Rb1);
        Rb1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        Rb1.setText("Fahrenheit");
        Rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb1ActionPerformed(evt);
            }
        });

        BgKonversi.add(Rb2);
        Rb2.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        Rb2.setText("Reamur");

        BgKonversi.add(Rb3);
        Rb3.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        Rb3.setText("Kelvin");
        Rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb3ActionPerformed(evt);
            }
        });

        BKonversi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BKonversi.setText("KONVERSI");
        BKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKonversiActionPerformed(evt);
            }
        });

        LHasil.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        LHasil.setForeground(new java.awt.Color(51, 51, 51));
        LHasil.setText("HASIL :");

        BgKonversi.add(Rb4);
        Rb4.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        Rb4.setText("Celcius");

        THasil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Rb3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(Rb4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(LHasil)
                                                .addGap(18, 18, 18)
                                                .addComponent(THasil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(BKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CbSkalaSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(16, 16, 16))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(LJudul)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbSkalaSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rb3)
                            .addComponent(Rb4)
                            .addComponent(Rb1))
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rb2)
                            .addComponent(BKonversi))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(THasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LHasil))
                        .addGap(25, 25, 25)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TSuhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TSuhuKeyTyped
         // Pembatasan input hanya angka, titik, dan backspace
    char c = evt.getKeyChar();
    if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != '.') {
        evt.consume();  // Membatasi input hanya angka dan titik
    } else {
        // Lakukan konversi otomatis jika input valid
        try {
            double suhuInput = Double.parseDouble(TSuhu.getText() + c);
            double hasilKonversi = 0.0;

            String skalaAsal = CbSkalaSuhu.getSelectedItem().toString();

            if (skalaAsal.equals("Celcius")) {
                if (Rb1.isSelected()) {
                    hasilKonversi = suhuInput * 9/5 + 32;
                } else if (Rb2.isSelected()) {
                    hasilKonversi = suhuInput * 4/5;
                } else if (Rb3.isSelected()) {
                    hasilKonversi = suhuInput + 273.15;
                }
            }
            // Tambahkan konversi lain sesuai kebutuhan

            THasil.setText("" + hasilKonversi);

        } catch (NumberFormatException e) {
            THasil.setText("Masukkan angka yang valid!");
        }
    }
    }//GEN-LAST:event_TSuhuKeyTyped

    private void BKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKonversiActionPerformed
        try {
        // Mengambil nilai suhu dari input
        double suhuInput = Double.parseDouble(TSuhu.getText());
        double hasilKonversi = 0.0;
        
        // Menentukan konversi berdasarkan skala asal dan tujuan
        String skalaAsal = CbSkalaSuhu.getSelectedItem().toString();
        
        // Cek pilihan skala tujuan di JRadioButton
        if (skalaAsal.equals("Celcius")) {
            if (Rb1.isSelected()) {
                hasilKonversi = suhuInput * 9/5 + 32;  // Celcius ke Fahrenheit
            } else if (Rb2.isSelected()) {
                hasilKonversi = suhuInput * 4/5;       // Celcius ke Reamur
            } else if (Rb3.isSelected()) {
                hasilKonversi = suhuInput + 273.15;    // Celcius ke Kelvin
            }
        } else if (skalaAsal.equals("Fahrenheit")) {
            if (Rb4.isSelected()) {
                hasilKonversi = (suhuInput - 32) * 5/9;  // Fahrenheit ke Celcius
            } else if (Rb2.isSelected()) {
                hasilKonversi = (suhuInput - 32) * 4/9;  // Fahrenheit ke Reamur
            } else if (Rb3.isSelected()) {
                hasilKonversi = (suhuInput - 32) * 5/9 + 273.15;  // Fahrenheit ke Kelvin
            }
        } else if (skalaAsal.equals("Reamur")) {
            if (Rb4.isSelected()) {
                hasilKonversi = suhuInput * 5/4;  // Reamur ke Celcius
            } else if (Rb1.isSelected()) {
                hasilKonversi = suhuInput * 9/4 + 32;  // Reamur ke Fahrenheit
            } else if (Rb3.isSelected()) {
                hasilKonversi = suhuInput * 5/4 + 273.15;  // Reamur ke Kelvin
            }
        } else if (skalaAsal.equals("Kelvin")) {
            if (Rb4.isSelected()) {
                hasilKonversi = suhuInput - 273.15;  // Kelvin ke Celcius
            } else if (Rb1.isSelected()) {
                hasilKonversi = (suhuInput - 273.15) * 9/5 + 32;  // Kelvin ke Fahrenheit
            } else if (Rb2.isSelected()) {
                hasilKonversi = (suhuInput - 273.15) * 4/5;  // Kelvin ke Reamur
            }
        }
        
        // Menampilkan hasil konversi
        THasil.setText("" + hasilKonversi);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!");
    }
    }//GEN-LAST:event_BKonversiActionPerformed

    private void TSuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSuhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TSuhuActionPerformed

    private void CbSkalaSuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbSkalaSuhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbSkalaSuhuActionPerformed

    private void Rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rb1ActionPerformed

    private void CbSkalaSuhuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbSkalaSuhuItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CbSkalaSuhuItemStateChanged

    private void Rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rb3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKonversiSuhuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BKonversi;
    private javax.swing.ButtonGroup BgKonversi;
    private javax.swing.JComboBox<String> CbSkalaSuhu;
    private javax.swing.JLabel LHasil;
    private javax.swing.JLabel LJudul;
    private javax.swing.JRadioButton Rb1;
    private javax.swing.JRadioButton Rb2;
    private javax.swing.JRadioButton Rb3;
    private javax.swing.JRadioButton Rb4;
    private javax.swing.JTextField THasil;
    private javax.swing.JTextField TSuhu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
